### ISSUE TITLE
I want iPod's artist list

### ISSUE THREAD

**Issue by LF-Studio** [chaosct/XBMC-iPod-plugin#1]
Hello.
I was spent long time for find this plugin.

This plugin is perfect for me, but I have just one request.
This plugin doesn't list artist list what iPod does like.

I want to add some codes to plugin.
Unfortunately, I don't know PYTHON. :'(

Could you upgrade plugin? ;)

**Comment by chaosct** [comment]
I'm sorry, @LF-Studio but I don't currently have an IPod or a Linux-based XBMC/Kodi, so I am unable to maintain this plugin :(

**Comment by sobralik** [comment]
Hi, 

@LF-Studio I have forked the plugin and made changes so that it lists artists first, then albums, then songs. The fork is here: https://github.com/stafio/XBMC-iPod-plugin

**Comment by chaosct** [comment]
Oh nice!

@stafio, is it ok for you if I specify that your fork is the one maintained in the description?

**Comment by sobralik** [comment]
@chaosct, yes that's ok with me. Thanks!
